---
name: WebService-Google-Sets
version: 0.01
author:
  - Dean Wilson <dean.wilson@gmail.com>
abstract: Perl access to Google Labs Sets site
license: perl
requires:
  CGI: 0
  LWP: 0
build_requires:
  Test::More: 0
provides:
  WebService::Google::Sets:
    file: lib/WebService/Google/Sets.pm
    version: 0.01
generated_by: Module::Build version 0.2611
